//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRJ300
{
    using System;
    using System.Collections.Generic;
    
    public partial class DummyTable
    {
        public int DummyTableID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string Name { get; set; }
        public string price { get; set; }
    }
}
